# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: agent
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo "Job1!!"
    displayName: 'Job 1 executed!!'


pool:
  name: agent2
  vmImage: ubuntu-latest

jobs:
- job: job2
  steps:
  - script: echo "Job2!!"
    displayName: "Job 2 Executed!!"